version: '3.8'

services:
  backend:
    build:
      context: ./jpa_practice
      dockerfile: Dockerfile
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JWT_SECRET=lemonEnglish8823
      - DB_PASSWORD=
    volumes:
      - ~/h2db:/root/h2db

  frontend:
    build:
      context: ./blue-community
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
