spring.profiles.active=local

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET}
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY:}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_KEY:}
spring.cloud.aws.s3.bucket=${AWS_S3_BUCKET:}
spring.cloud.aws.region.static=${AWS_REGION:us-east-1}

logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.multipart=DEBUG