name: Backend CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 깃허브 코드 가져오기
      - name: Checkout repository
        uses: actions/checkout@v3

      # 백엔드 버전에 맞는 자바 21 설치
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      # Gradle 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 스프링 부트 프로젝트 빌드
      - name: Build with Gradle
        run: ./gradlew clean build -x test
